import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./Redux/StoreProvider";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
          <Header/>
       <div className="flex items-start justify-center">
        <Sidebar/>
       {children}
       </div>
      
      </body>
      </StoreProvider>
    </html>
  );
}
